# Especifica la versión de la API de Kubernetes utilizada para el recurso Deployment
apiVersion: apps/v1
# Indica que este manifiesto describe un Deployment
kind: Deployment
# Metadatos del recurso, como el nombre del deployment
metadata:
  name: mi-app-python
spec:
  replicas: 2  # Número de réplicas (pods) que se desean ejecutar
  selector:
    matchLabels:
      app: mi-app-python  # Selector para identificar los pods gestionados por este deployment
  template:
    metadata:
      labels:
        app: mi-app-python  # Etiqueta que se asigna a los pods creados por este deployment
    spec:
      containers:
        - name: contenedor-python  # Nombre del contenedor dentro del pod
          image: proyectoredesslfj.azurecr.io/proyectoredesslfj.azurecr.io/mi-app-python:latest  # Imagen Docker a usar
          imagePullPolicy: Always  # Política para obtener la imagen (siempre descargar la última versión)
          ports:
            - containerPort: 5000  # Puerto expuesto por el contenedor
      imagePullSecrets:
        - name: acr-secret  # Secreto para acceder al registro privado de imágenes
